### ISSUE TITLE
Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:CALCULATE_FRIP

### ISSUE THREAD

**Issue by jmzvillarreal** [nf-core/cutandrun#86] opened 2022-01-13 13:29 UTC
Hi,
I am getting an error running the pipelne using docker profile. Below I paste pipeline info :+1: 
Run Name: gigantic_ekeblad

####################################################
####################################################
The exit status of the task that caused the workflow execution to fail was: 1.
The full error message was:

Error executing process > 'NFCORE_CUTANDRUN:CUTANDRUN:CALCULATE_FRIP (ABE24-N1X_R1)'

Caused by:
  Process `NFCORE_CUTANDRUN:CUTANDRUN:CALCULATE_FRIP (ABE24-N1X_R1)` terminated with an error exit status (1)

Command executed:

  frip.py \
      --bams "*.bam" \
      --peaks "*.bed" \
      --threads 12 \
      --outpath .
  
  python --version | grep -E -o "([0-9]{1,}\.)+[0-9]{1,}" > python.version.txt

Command exit status:
  1

Command output:
  Calculating ABE24-N1X_R1.target.markdup.bam using ABE24-N1X_R1.peaks.bed.stringent.bed

Command error:
  Matplotlib created a temporary config/cache directory at /tmp/matplotlib-vkw9ufgl because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
  Traceback (most recent call last):
    File "/home/jmartinezv/.nextflow/assets/nf-core/cutandrun/bin/frip.py", line 44, in <module>
      reads_at_peaks = cr.run()
    File "/opt/conda/envs/packages/lib/python3.8/site-packages/deeptools/countReadsPerBin.py", line 356, in run
      imap_res = mapReduce.mapReduce([],
    File "/opt/conda/envs/packages/lib/python3.8/site-packages/deeptools/mapReduce.py", line 85, in mapReduce
      bed_interval_tree = GTF(bedFile, defaultGroup=defaultGroup, transcriptID=transcriptID, exonID=exonID, transcript_id_designator=transcript_id_designator, keepExons=keepExons)
    File "/opt/conda/envs/packages/lib/python3.8/site-packages/deeptoolsintervals/parse.py", line 591, in __init__
      ftype = self.inferType(fp, line, labelColumn)
    File "/opt/conda/envs/packages/lib/python3.8/site-packages/deeptoolsintervals/parse.py", line 166, in inferType
      raise RuntimeError('{0} does not seem to be a recognized file type!'.format(self.filename))
  RuntimeError: ABE24-N1X_R1.peaks.bed.stringent.bed does not seem to be a recognized file type!

Work dir:
  /local/ljmartinezv/IreneF_Cut_Run/work/53/ddece62198fb63faeb9c87bd4c48cd

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

The workflow was completed at 2022-01-04T14:55:17.532437+01:00 (duration: 5h 9m 26s)

The command used to launch the workflow was as follows:

  nextflow run nf-core/cutandrun --input samplesheet_N1X.csv --genome hg19 --spikein_bowtie2 's3://ngi-igenomes/igenomes/Saccharomyces_cerevisiae/NCBI/build3.1/Sequence/Bowtie2Index/' --spikein_fasta 's3://ngi-igenomes/igenomes/Saccharomyces_cerevisiae/NCBI/build3.1/Sequence/Bowtie2Index/genome.fa' --skip_trimming --max_memory 60GB --outdir /local/ljmartinezv/IreneF_Cut_Run/results_N1X -profile docker

Pipeline Configuration:
-----------------------
 - revision: master
 - runName: gigantic_ekeblad
 - containerEngine: docker
 - launchDir: /local/ljmartinezv/IreneF_Cut_Run
 - workDir: /local/ljmartinezv/IreneF_Cut_Run/work
 - projectDir: /home/jmartinezv/.nextflow/assets/nf-core/cutandrun
 - userName: jmartinezv
 - profile: docker
 - configFiles: /home/jmartinezv/.nextflow/assets/nf-core/cutandrun/nextflow.config
 - input: samplesheet_N1X.csv
 - outdir: /local/ljmartinezv/IreneF_Cut_Run/results_N1X
 - genome: hg19
 - bowtie2: s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Sequence/Bowtie2Index/
 - gtf: s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf
 - blacklist: /home/jmartinezv/.nextflow/assets/nf-core/cutandrun/assets/blacklists/hg19-blacklist.bed
 - spikein_bowtie2: s3://ngi-igenomes/igenomes/Saccharomyces_cerevisiae/NCBI/build3.1/Sequence/Bowtie2Index/
 - spikein_fasta: s3://ngi-igenomes/igenomes/Saccharomyces_cerevisiae/NCBI/build3.1/Sequence/Bowtie2Index/genome.fa
 - fasta: s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
 - igenomes_base: s3://ngi-igenomes/igenomes/
 - gene_bed: s3://ngi-igenomes/igenomes//Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.bed
 - skip_trimming: true
 - max_memory: 60GB
 - Date Started: 2022-01-04T09:45:51.189377+01:00
 - Date Completed: 2022-01-04T14:55:17.532437+01:00
 - Pipeline script file path: /home/jmartinezv/.nextflow/assets/nf-core/cutandrun/main.nf
 - Pipeline script hash ID: 8e8fba88a8cec012928bfc5c32179c0e
 - Pipeline repository Git URL: https://github.com/nf-core/cutandrun
 - Pipeline repository Git Commit: 81ede3365da0f9bf7b7efdcf07acb2fb2c913c33
 - Pipeline Git branch/tag: master
 - Nextflow Version: 21.04.3
 - Nextflow Build: 5560
 - Nextflow Compile Timestamp: 21-07-2021 15:09 UTC

Most striking thing is that it is working just fine in another set of samples.
Thanks very much in advance,
Best.
Jaime.

**Comment by chris-cheshire** [comment] 2022-01-17 09:10
Hi thanks for your Issue, this is fixed in the 1.1 version and is usually caused by empty input files (no peaks). You can either use the dev version of the pipeline `-r dev` or wait until the release. Cheers, Chris

**Closed** 2022-01-17 09:11 UTC
Labels: bug, duplicate
