### ISSUE TITLE
Not a valid path value type: java.util.LinkedHashMap ([id:spikein_fasta])

### ISSUE THREAD

**Issue by Gin-Wang** [nf-core/cutandrun#187] opened 2023-03-16 01:39 UTC
### Description of the bug

I met errors in using cutandrun pipeline. In 3.1 it goes well till TRIMGALORE and FASTQC and gets error 'NFCORE_CUTANDRUN:CUTANDRUN:ALIGN_BOWTIE2:BOWTIE2_TARGET_ALIGN (2)' Caused by: Not a valid path value type: java.util.LinkedHashMap ([id:spikein_fasta]). 

The error occured in 3.0 version and could not run the pipeline. All input is reachable and readable by anyone.  It is strange that  I have a completed process of NFCORE_CUTANDRUN:CUTANDRUN:ALIGN_BOWTIE2:BOWTIE2_SPIKEIN_ALIGN, but it still got Not a valid path value type in spike in fasta. 

I have posted this in the slack channels, and several people met the same error just like me. I wonder if there is a bug or just mistakes in the command line.

here the parameters I’m trying.

### Command used and terminal output

```console
INPUT=/.../cuttag/samplesheet.csv
OUTDIR=/.../cuttag/
FASTA=/home/Reference/GRCh38/GRCh38.primary_assembly.genome.fa
GTF=/home/Reference/GRCh38/gencode.v41.primary_assembly.annotation.gtf
BLACK=/home/Reference/GRCh38/hg38-blacklist.v3.bed
SPIKEIN_FASTA=/home/Reference/SpikeIn/Escherichia_coli_K_12_DH10B/NCBI/2008-03-17/Sequence/WholeGenomeFasta/genome.fa
SPIKEIN_INDEX=/home/Reference/SpikeIn/Escherichia_coli_K_12_DH10B/NCBI/2008-03-17/Sequence/Bowtie2Index
 
nextflow run /.../nf-core-cutandrun-3.1/ --input ${INPUT} --outdir ${OUTDIR} --fasta ${FASTA} --gtf ${GTF} --igenomes_ignore --max_memory 150.GB -profile singularity --macs_gsize 2700000000 --blacklist ${BLACK} --save_merged_fastq --replicate_threshold 2 --spikein_fasta $SPIKEIN_FASTA --spikein_bowtie2 ${SPIKEIN_INDEX} --save_reference --use_control false -bg
```

### Relevant files

[pipeline_report.txt](https://github.com/nf-core/cutandrun/files/10985871/pipeline_report.txt)
[nextflow.log](https://github.com/nf-core/cutandrun/files/10985875/nextflow.log)

**Comment by cjfields** [comment] 2023-03-21 04:18
I had a very similar issue that occurred when I let the workflow index a given FASTA file, which seems to be the default for other workflows when giving a `--fasta` sequence and no index file.  If I supply the bowtie2 index path using `--bowtie2` it works fine, which makes me suspect there is some difference in the input channels (e.g. between when the workflow generates the index vs the index being provided on command line).

**Comment by Gin-Wang** [comment] 2023-03-21 06:28
I have tested it as @cjfields mentioned, using the existing bowtie2 index instead of generating an index by the pipeline itself. It seems to go well now and have passed the alignment process.

**Comment by chris-cheshire** [comment] 2023-04-13 15:19
great

**Comment by chris-cheshire** [comment] 2023-04-17 14:40
Hi @Gin-Wang @cjfields , I have managed to reproduce and fix the error. It was a channel format issue. its fixed in the commit below and will be in the next release https://github.com/luslab/cutandrun/commit/cdfc3560b1d3bb819cd3df63740ff7eb613b4db6

**Comment by cjfields** [comment] 2023-04-17 14:58
Awesome. thx @chris-cheshire !

**Closed** 2023-04-19 07:53 UTC
Labels: bug

**Comment by sme229** [comment] 2024-09-17 23:16
Hi @chris-cheshire I'm getting the same error trying to run scnanoseq pipeline
